---

- name: Install repository Gluster
  yum: 
    name: centos-release-gluster9
    state: present
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7" 
  tags: gluster

- name: Install repository Gluster
  dnf: 
    name: centos-release-gluster9
    state: present
  when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8") or (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "9") 
  tags: gluster

- name: ensure a list of gluster packages installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - heketi
    - glusterfs-fuse
    - glusterfs
    - gluster-block
    - glusterfs-events
    - glusterfs-cli
    - glusterfs-libs
    - glusterfs-server
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7" 
  tags: gluster

- name: ensure a list of gluster packages installed
  dnf:
    name: "{{ packages }}"
  vars:
    packages:
    - glusterfs
    - glusterfs-libs
    - glusterfs-server
  when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8") or (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "9")
  tags: gluster



- name: enable Glusterd service
  systemd:
    name: glusterd
    enabled: yes
  tags: gluster


- name: Make sure Gluster service is running
  systemd:
    state: started
    name: glusterd
  tags: gluster
