---

- name: removing firewall rules for Gluster service
  firewalld:
    service: glusterfs
    permanent: true
    state: disabled
  tags: firewall

- name: removing firewall rules for 24007/tcp Gluster Daemon 
  firewalld:
    port: 24007/tcp
    permanent: true
    state: disabled
  tags: firewall
  
- name: removing firewall rules for 49152-49251/tcp Gluster brick port
  firewalld:
    port: 49152-49251/tcp
    permanent: true
    state: disabled
  tags: firewall

- name: removing firewall rules for 38465-38469/tcp Gluster NFS Service 
  firewalld:
    port: 38465-38469/tcp
    permanent: true
    state: disabled
  tags: firewall

- name: removing firewall rules for 111/TCP Portmapper 
  firewalld:
    port: 111/tcp 
    permanent: true
    state: disabled
  tags: firewall
  
- name: removing firewall rules for 111/UDP Portmapper 
  firewalld:
    port: 111/udp
    permanent: true
    state: disabled
  tags: firewall

- name: removing firewall rules for 2049/tcp NFS Service 
  firewalld:
    port: 2049/tcp
    permanent: true
    state: disabled
  tags: firewall
  
- name: removing firewall rules for 963/udp Gluster NFS's Lock Manager
  firewalld:
    port: 963/udp
    permanent: true
    state: disabled
  tags: firewall
  
- name: removing firewall rules for 139/tcp Netbios service
  firewalld:
    port: 139/tcp
    permanent: true
    state: disabled
  tags: firewall
  
- name: removing firewall rules for 445/tcp CIFS Protocol
  firewalld:
    port: 445/tcp
    permanent: true
    state: disabled
  tags: firewall

- name: removing firewall rules for 965/tcp Gluster NFS's Lock Manager
  firewalld:
    port: 965/tcp
    permanent: true
    state: disabled
  notify: Reloading firewalld rules
  tags: firewall

