---

- name: disable Glusterd service
  systemd:
    name: glusterd
    enabled: false
  tags: gluster

- name: Make sure Gluster service is stopped
  systemd:
    state: stopped
    name: glusterd
  tags: gluster


- name: main | uninstall Gluster\ packages
  yum: >
    pkg={{ item }}
    state=absent
  with_items:
    - heketi
    - glusterfs-fuse
    - glusterfs
    - gluster-block
    - glusterfs-events
    - glusterfs-cli
    - glusterfs-libs
    - glusterfs-server
  when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7" 
  tags: gluster

- name: main | uninstall Gluster packages
  dnf: >
    pkg={{ item }}
    state=absent
  with_items:
    - glusterfs
    - glusterfs-libs
    - glusterfs-server
  when: (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8") or (ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "9") 
  tags: gluster  

- name: remove Gluster repository 
  yum: name=centos-release-gluster9 state=absent
  tags: gluster
